env:
  browser: true
  es2022: true
extends:
  - 'eslint:recommended'
  - 'plugin:vue/vue3-essential'
  - 'plugin:@typescript-eslint/recommended'
  - '@nuxtjs/eslint-config-typescript'
  - 'plugin:storybook/recommended'
  - '@vue/prettier'
overrides: []
parser: 'vue-eslint-parser'
parserOptions:
  parser: '@typescript-eslint/parser'
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
  - '@typescript-eslint'
rules: { 'vue/no-v-model-argument': 0, 'vue/multi-word-component-names': 'off' }
